language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4snapshot

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs ./src
  - vendor/bin/phpcbf ./src
  - vendor/bin/psalm --show-info=false