version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ../pattern-php:/var/www/html/pattern-php
    ports:
      - "9000:9000"

  composer:
    restart: 'no'
    image: composer:latest
    command: "-v"
    volumes:
      - .:/app